name: acustica
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - aiodns=3.5.0=py313h06a4308_0
  - aiohappyeyeballs=2.6.1=py313h06a4308_0
  - aiohttp=3.12.15=py313hb25bd0a_0
  - aiosignal=1.4.0=py313h06a4308_0
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - anyio=4.7.0=py313h06a4308_0
  - aom=3.6.0=h6a678d5_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py313h5eee18b_1
  - asttokens=3.0.0=py313h06a4308_0
  - async-lru=2.0.4=py313h06a4308_0
  - audioop-lts=0.2.2=py313h54dd161_0
  - audioread=3.0.1=py313h78bf25f_2
  - babel=2.16.0=py313h06a4308_0
  - beautifulsoup4=4.13.5=py313h06a4308_0
  - blas=2.134=openblas
  - blas-devel=3.9.0=34_h1ea3ea9_openblas
  - bleach=6.2.0=py313h06a4308_0
  - brotli-python=1.0.9=py313h6a678d5_9
  - brotlicffi=1.0.9.2=py313h6a678d5_1
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hef5626c_0
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cairo=1.18.4=h44eff21_0
  - certifi=2025.10.5=py313h06a4308_0
  - cffi=1.17.1=py313h1fdaa30_1
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.1=py313h06a4308_0
  - contourpy=1.3.1=py313hdb19cb5_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h1110e0f_3
  - dav1d=1.2.1=h5eee18b_0
  - debugpy=1.8.11=py313h6a678d5_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - discord.py=2.3.2=pyhd8ed1ab_0
  - distro=1.9.0=pyhd8ed1ab_1
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.7.1=h6a678d5_0
  - ffmpeg=4.4.0=hca11adc_0
  - fontconfig=2.15.0=h2c49b7f_0
  - fonttools=4.55.3=py313h5eee18b_0
  - freetype=2.13.3=h4a9f257_0
  - fribidi=1.0.10=h7b6447c_0
  - gettext=0.25.1=h3f43e3d_1
  - gettext-tools=0.25.1=h3f43e3d_1
  - giflib=5.2.2=h5eee18b_0
  - gmp=6.3.0=h6a678d5_0
  - gnutls=3.6.15=he1e5248_0
  - graphite2=1.3.14=h295c915_1
  - h11=0.16.0=py313h06a4308_0
  - harfbuzz=10.2.0=hdfddeaa_1
  - httpcore=1.0.9=py313h06a4308_0
  - httpx=0.28.1=py313h06a4308_0
  - icu=73.1=h6a678d5_0
  - idna=3.7=py313h06a4308_0
  - ipykernel=6.29.5=py313h06a4308_1
  - ipython=9.1.0=py313h06a4308_0
  - ipython_pygments_lexers=1.1.1=py313h06a4308_0
  - ipywidgets=8.1.5=py313h06a4308_0
  - jedi=0.19.2=py313h06a4308_0
  - jinja2=3.1.6=py313h06a4308_0
  - jiter=0.11.0=py313h5c7d99a_1
  - joblib=1.5.1=py313h06a4308_0
  - jpeg=9e=h5eee18b_3
  - json5=0.9.25=py313h06a4308_0
  - jsonschema=4.25.0=py313h06a4308_0
  - jsonschema-specifications=2023.7.1=py313h06a4308_0
  - jupyter=1.1.1=py313h06a4308_0
  - jupyter-lsp=2.2.5=py313h06a4308_0
  - jupyter_client=8.6.3=py313h06a4308_0
  - jupyter_console=6.6.3=py313h06a4308_1
  - jupyter_core=5.8.1=py313h06a4308_0
  - jupyter_events=0.12.0=py313h06a4308_0
  - jupyter_server=2.16.0=py313h06a4308_0
  - jupyter_server_terminals=0.5.3=py313h06a4308_0
  - jupyterlab=4.4.6=py313h06a4308_0
  - jupyterlab_pygments=0.3.0=py313h06a4308_0
  - jupyterlab_server=2.27.3=py313h06a4308_0
  - jupyterlab_widgets=3.0.15=py313h06a4308_0
  - kiwisolver=1.4.8=py313h6a678d5_0
  - lame=3.100=h7b6447c_0
  - lazy_loader=0.4=py313h06a4308_0
  - lcms2=2.16=h92b89f2_1
  - ld_impl_linux-64=2.40=h12ee557_0
  - leptonica=1.82.0=hfdeec58_3
  - lerc=4.0.0=h6a678d5_0
  - libabseil=20250127.0=cxx17_h6a678d5_0
  - libarchive=3.7.7=hfab0078_0
  - libasprintf=0.25.1=h3f43e3d_1
  - libasprintf-devel=0.25.1=h3f43e3d_1
  - libavif=1.1.1=h5eee18b_0
  - libblas=3.9.0=34_h59b9bed_openblas
  - libcblas=3.9.0=34_he106b2a_openblas
  - libcups=2.4.2=h252cb56_2
  - libcurl=8.15.0=hc1efc7f_0
  - libdeflate=1.22=h5eee18b_0
  - libdrm=2.4.124=h5eee18b_0
  - libedit=3.1.20230828=h5eee18b_0
  - libegl=1.7.0=h5eee18b_2
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hdbd6064_1
  - libffi=3.4.4=h6a678d5_1
  - libflac=1.4.3=h59595ed_0
  - libgcc=15.1.0=h767d61c_4
  - libgcc-ng=15.1.0=h69a702a_4
  - libgettextpo=0.25.1=h3f43e3d_1
  - libgettextpo-devel=0.25.1=h3f43e3d_1
  - libgfortran=15.1.0=h69a702a_4
  - libgfortran-ng=15.1.0=h69a702a_4
  - libgfortran5=15.1.0=hcea5267_4
  - libgl=1.7.0=h5eee18b_2
  - libglib=2.84.2=h37c7471_0
  - libglvnd=1.7.0=h5eee18b_2
  - libglx=1.7.0=h5eee18b_2
  - libgomp=15.1.0=h767d61c_4
  - libiconv=1.18=h3b78370_2
  - libidn2=2.3.4=h5eee18b_0
  - libkrb5=1.21.3=h520c7b4_4
  - liblapack=3.9.0=34_h7ac8fdf_openblas
  - liblapacke=3.9.0=34_he2f377e_openblas
  - libllvm15=15.0.7=he89c38a_4
  - libmpdec=4.0.0=h5eee18b_0
  - libnghttp2=1.57.0=h2d74bed_0
  - libogg=1.3.5=h27cfd23_1
  - libopenblas=0.3.30=pthreads_h94d23a6_2
  - libopus=1.3.1=h5eee18b_1
  - libpciaccess=0.18=h5eee18b_0
  - libpng=1.6.39=h5eee18b_0
  - libpq=17.4=h02b6914_2
  - libprotobuf=5.29.3=h3cdef7c_1
  - librosa=0.11.0=pyhd8ed1ab_0
  - libsndfile=1.2.2=hc60ed4a_1
  - libsodium=1.0.18=h7b6447c_0
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx=15.1.0=h8f9b012_4
  - libstdcxx-ng=15.1.0=h4852527_4
  - libtasn1=4.20.0=ha30cf84_0
  - libtheora=1.2.0=h49481b2_0
  - libtiff=4.7.0=hde9077f_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libuv=1.48.0=h5eee18b_0
  - libvorbis=1.3.7=h7b6447c_0
  - libvpx=1.13.1=h6a678d5_0
  - libwebp=1.3.2=h9f374a3_1
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.17.0=h9b100fa_0
  - libxkbcommon=1.9.1=h69220b7_0
  - libxml2=2.13.8=hfdd30dd_0
  - libzlib=1.3.1=hb25bd0a_0
  - llvmlite=0.45.1=py313hdd307be_0
  - lmdb=0.9.31=hb25bd0a_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=3.0.2=py313h5eee18b_0
  - matplotlib=3.10.6=py313h06a4308_0
  - matplotlib-base=3.10.6=py313h4948728_0
  - matplotlib-inline=0.1.6=py313h06a4308_0
  - mesalib=25.1.5=h31e3550_0
  - mistune=3.1.2=py313h06a4308_0
  - mpg123=1.32.9=hc50e24c_0
  - msgpack-python=1.1.1=py313h6a678d5_0
  - mysql=8.4.0=h721767e_2
  - nbclient=0.10.2=py313h06a4308_0
  - nbconvert=7.16.6=py313h06a4308_0
  - nbconvert-core=7.16.6=py313h06a4308_0
  - nbconvert-pandoc=7.16.6=py313h06a4308_0
  - nbformat=5.10.4=py313h06a4308_0
  - ncurses=6.5=h7934f7d_0
  - nest-asyncio=1.6.0=py313h06a4308_0
  - nettle=3.7.3=hbbd107a_1
  - notebook=7.4.5=py313h06a4308_0
  - notebook-shim=0.2.4=py313h06a4308_0
  - numba=0.62.1=py313hd8e3f9f_0
  - numpy=2.3.3=py313h816806e_0
  - numpy-base=2.3.3=py313h7203c5b_0
  - openai=1.109.1=pyhd8ed1ab_0
  - openblas=0.3.30=pthreads_h6ec200e_2
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.2=h0d4d230_1
  - openldap=2.6.10=h8e75217_0
  - openssl=3.5.4=h26f9b46_0
  - overrides=7.4.0=py313h06a4308_0
  - packaging=25.0=py313h06a4308_0
  - pandoc=2.12=h06a4308_3
  - pandocfilters=1.5.1=py313h06a4308_0
  - parso=0.8.4=py313h06a4308_0
  - pcre2=10.42=hebb0a14_1
  - pexpect=4.9.0=py313h06a4308_0
  - pillow=11.3.0=py313hb1c3d2d_0
  - pip=25.1=pyhc872135_2
  - pixman=0.46.4=h7934f7d_0
  - platformdirs=4.3.7=py313h06a4308_0
  - pooch=1.8.2=py313h06a4308_0
  - prometheus_client=0.21.1=py313h06a4308_0
  - prompt-toolkit=3.0.43=py313h06a4308_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - psutil=5.9.0=py313h5eee18b_1
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycares=4.10.0=py313ha137689_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pydantic=2.11.9=pyh3cfb1c2_0
  - pydantic-core=2.33.2=py313h4b2b08d_0
  - pygments=2.19.1=py313h06a4308_0
  - pyparsing=3.2.0=py313h06a4308_0
  - pyqt=6.7.1=py313h8dad735_2
  - pyqt6-sip=13.9.1=py313h6ce4db3_2
  - pysocks=1.7.1=py313h06a4308_0
  - pysoundfile=0.13.1=pyhd8ed1ab_0
  - python=3.13.7=h7e8bc2b_100_cp313
  - python-dateutil=2.9.0post0=py313h06a4308_2
  - python-fastjsonschema=2.20.0=py313h06a4308_0
  - python-json-logger=3.2.1=py313h06a4308_0
  - python_abi=3.13=0_cp313
  - pyyaml=6.0.2=py313h5eee18b_0
  - pyzmq=26.2.0=py313h6a678d5_0
  - qtbase=6.7.3=h10a5587_4
  - qtconsole=5.6.1=py313h06a4308_1
  - qtdeclarative=6.7.3=h7934f7d_1
  - qtpy=2.4.1=py313h06a4308_0
  - qtsvg=6.7.3=he4bddd1_1
  - qttools=6.7.3=h5a8de97_1
  - qtwebchannel=6.7.3=h7934f7d_1
  - qtwebsockets=6.7.3=h7934f7d_1
  - readline=8.3=hc2a1206_0
  - referencing=0.30.2=py313h06a4308_0
  - requests=2.32.5=py313h06a4308_0
  - rfc3339-validator=0.1.4=py313h06a4308_0
  - rfc3986-validator=0.1.1=py313h06a4308_0
  - rpds-py=0.22.3=py313h4aa5aa6_0
  - scikit-learn=1.7.1=py313h06d7b56_0
  - scipy=1.16.2=py313he2bc341_0
  - send2trash=1.8.2=py313h06a4308_1
  - setuptools=72.1.0=py313h06a4308_0
  - sip=6.10.0=py313h6a678d5_0
  - six=1.17.0=py313h06a4308_0
  - sniffio=1.3.0=py313h06a4308_0
  - soupsieve=2.5=py313h06a4308_0
  - soxr=0.1.3=h0b41bf4_3
  - soxr-python=0.5.0.post1=py313h46c70d0_1
  - spirv-tools=2025.1=hdb19cb5_0
  - sqlite=3.50.2=hb25bd0a_1
  - stack_data=0.2.0=pyhd3eb1b0_0
  - standard-aifc=3.13.0=py313h78bf25f_2
  - standard-chunk=3.13.0=pyhd8ed1ab_0
  - standard-sunau=3.13.0=py313h78bf25f_2
  - tbb=2021.8.0=hdb19cb5_0
  - terminado=0.17.1=py313h06a4308_0
  - tesseract=5.2.0=h6a678d5_2
  - threadpoolctl=3.5.0=py313h7040dfc_0
  - tinycss2=1.4.0=py313h06a4308_0
  - tk=8.6.15=h54e0aa7_0
  - tornado=6.5.1=py313h5eee18b_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=py313h06a4308_0
  - typing-extensions=4.15.0=py313h06a4308_0
  - typing-inspection=0.4.1=pyhd8ed1ab_0
  - typing_extensions=4.15.0=py313h06a4308_0
  - urllib3=2.5.0=py313h06a4308_0
  - uvloop=0.21.0=py313h5eee18b_0
  - wcwidth=0.2.13=py313h06a4308_0
  - webencodings=0.5.1=py313h06a4308_2
  - websocket-client=1.8.0=py313h06a4308_0
  - wheel=0.45.1=py313h06a4308_0
  - widgetsnbextension=4.0.13=py313h06a4308_0
  - x264=1!161.3030=h7f98852_1
  - xcb-util=0.4.1=h5eee18b_2
  - xcb-util-cursor=0.1.5=h5eee18b_0
  - xcb-util-image=0.4.0=h5eee18b_2
  - xcb-util-keysyms=0.4.1=h5eee18b_0
  - xcb-util-renderutil=0.3.10=h5eee18b_0
  - xcb-util-wm=0.4.2=h5eee18b_0
  - xkeyboard-config=2.44=h5eee18b_0
  - xorg-libice=1.1.2=h9b100fa_0
  - xorg-libsm=1.2.6=h9b100fa_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxfixes=6.0.1=h9b100fa_0
  - xorg-libxrandr=1.5.4=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-libxshmfence=1.3.3=h9b100fa_0
  - xorg-libxxf86vm=1.1.6=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.5=h6a678d5_0
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=h11fc155_0
  - pip:
      - attrs==25.3.0
      - click==8.1.8
      - discord-py==2.6.3
      - frozenlist==1.7.0
      - gtts==2.5.4
      - multidict==6.6.4
      - pandas==2.3.3
      - propcache==0.3.2
      - pydub==0.25.1
      - pynacl==1.5.0
      - python-dotenv==1.1.1
      - pyttsx3==2.99
      - pytz==2025.2
      - sounddevice==0.5.3
      - tzdata==2025.2
      - yarl==1.20.1
prefix: /home/panghys/miniconda3/envs/acustica
